const BRAND = { site: 'Pick My Cabin' };

// Cruise lines and ships are a starter directory to search/browse — not tied
// to any single line, and meant to grow. "Can't find your ship" adds new
// entries the same way real reviews do.
const LINES = [
  { id: 'cunard', name: 'Cunard' },
  { id: 'royal-caribbean', name: 'Royal Caribbean' },
  { id: 'celebrity', name: 'Celebrity Cruises' },
  { id: 'princess', name: 'Princess Cruises' },
  { id: 'msc', name: 'MSC Cruises' },
  { id: 'holland-america', name: 'Holland America Line' },
  { id: 'regent', name: 'Regent Seven Seas Cruises' },
  { id: 'silversea', name: 'Silversea' },
  { id: 'oceania', name: 'Oceania Cruises' },
  { id: 'ncl', name: 'Norwegian Cruise Line' },
  { id: 'disney', name: 'Disney Cruise Line' },
  { id: 'viking', name: 'Viking Ocean Cruises' },
  { id: 'po-cruises', name: 'P&O Cruises' },
];

function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

// IDs are just the slugified ship name (matches the original hand-written
// ids, so existing reviews keep pointing at the right ship) — except where
// names are generic enough to collide (e.g. Oceania's single-word ships),
// which get the line as a prefix for uniqueness.
function shipList(lineId, names, { prefixed = false } = {}) {
  return names.map((name) => ({
    id: prefixed ? `${lineId}-${slugify(name)}` : slugify(name),
    lineId,
    name,
  }));
}

const SHIPS = [
  ...shipList('cunard', ['Queen Mary 2', 'Queen Victoria', 'Queen Elizabeth', 'Queen Anne']),
  ...shipList('royal-caribbean', [
    'Icon of the Seas',
    'Star of the Seas',
    'Utopia of the Seas',
    'Wonder of the Seas',
    'Symphony of the Seas',
    'Harmony of the Seas',
    'Oasis of the Seas',
    'Allure of the Seas',
    'Odyssey of the Seas',
    'Spectrum of the Seas',
    'Anthem of the Seas',
    'Ovation of the Seas',
    'Quantum of the Seas',
    'Freedom of the Seas',
    'Liberty of the Seas',
    'Independence of the Seas',
    'Navigator of the Seas',
    'Mariner of the Seas',
    'Voyager of the Seas',
    'Explorer of the Seas',
    'Adventure of the Seas',
    'Radiance of the Seas',
    'Brilliance of the Seas',
    'Serenade of the Seas',
    'Jewel of the Seas',
    'Vision of the Seas',
    'Grandeur of the Seas',
    'Enchantment of the Seas',
  ]),
  ...shipList('celebrity', [
    'Celebrity Xcel',
    'Celebrity Beyond',
    'Celebrity Apex',
    'Celebrity Edge',
    'Celebrity Ascent',
    'Celebrity Silhouette',
    'Celebrity Reflection',
    'Celebrity Eclipse',
    'Celebrity Equinox',
    'Celebrity Solstice',
    'Celebrity Summit',
    'Celebrity Constellation',
    'Celebrity Infinity',
    'Celebrity Millennium',
  ]),
  ...shipList('princess', [
    'Star Princess',
    'Sun Princess',
    'Discovery Princess',
    'Enchanted Princess',
    'Sky Princess',
    'Majestic Princess',
    'Regal Princess',
    'Royal Princess',
    'Emerald Princess',
    'Caribbean Princess',
    'Crown Princess',
    'Ruby Princess',
    'Diamond Princess',
    'Sapphire Princess',
    'Island Princess',
    'Coral Princess',
  ]),
  ...shipList('msc', [
    'MSC World America',
    'MSC World Europa',
    'MSC Euribia',
    'MSC Seascape',
    'MSC Seashore',
    'MSC Grandiosa',
    'MSC Virtuosa',
    'MSC Bellissima',
    'MSC Meraviglia',
    'MSC Preziosa',
    'MSC Divina',
    'MSC Fantasia',
    'MSC Splendida',
    'MSC Magnifica',
    'MSC Musica',
    'MSC Orchestra',
    'MSC Poesia',
    'MSC Armonia',
    'MSC Lirica',
    'MSC Opera',
  ]),
  ...shipList('holland-america', [
    'Rotterdam',
    'Nieuw Statendam',
    'Koningsdam',
    'Nieuw Amsterdam',
    'Eurodam',
    'Oosterdam',
    'Westerdam',
    'Zuiderdam',
    'Noordam',
    'Volendam',
    'Zaandam',
  ]),
  ...shipList('regent', [
    'Seven Seas Grandeur',
    'Seven Seas Splendor',
    'Seven Seas Explorer',
    'Seven Seas Voyager',
    'Seven Seas Mariner',
    'Seven Seas Navigator',
  ]),
  ...shipList('silversea', [
    'Silver Nova',
    'Silver Ray',
    'Silver Moon',
    'Silver Dawn',
    'Silver Muse',
    'Silver Spirit',
    'Silver Whisper',
    'Silver Shadow',
    'Silver Wind',
    'Silver Cloud',
    'Silver Origin',
    'Silver Endeavour',
  ]),
  ...shipList('oceania', ['Vista', 'Allura', 'Marina', 'Riviera', 'Sirena', 'Regatta', 'Insignia', 'Nautica'], {
    prefixed: true,
  }),
  ...shipList('ncl', [
    'Norwegian Aqua',
    'Norwegian Prima',
    'Norwegian Viva',
    'Norwegian Encore',
    'Norwegian Bliss',
    'Norwegian Joy',
    'Norwegian Escape',
    'Norwegian Getaway',
    'Norwegian Breakaway',
    'Norwegian Epic',
    'Norwegian Jade',
    'Norwegian Gem',
    'Norwegian Pearl',
    'Norwegian Star',
    'Norwegian Sun',
    'Norwegian Sky',
    'Norwegian Spirit',
    'Pride of America',
  ]),
  ...shipList('disney', [
    'Disney Destiny',
    'Disney Treasure',
    'Disney Wish',
    'Disney Fantasy',
    'Disney Dream',
    'Disney Magic',
    'Disney Wonder',
  ]),
  ...shipList('viking', [
    'Viking Vela',
    'Viking Saturn',
    'Viking Neptune',
    'Viking Mars',
    'Viking Jupiter',
    'Viking Venus',
    'Viking Orion',
    'Viking Sky',
    'Viking Sea',
    'Viking Star',
  ]),
  ...shipList('po-cruises', ['Iona', 'Arvia', 'Britannia', 'Azura', 'Ventura', 'Aurora', 'Arcadia']),
];

const TAGS = [
  'Quiet',
  'Noisy',
  'Great view',
  'Obstructed view',
  'Spacious',
  'Small bathroom',
  'Close to lifts',
  'Long walk to lifts',
  'Balcony overlooked',
  'Good storage',
];

